### ISSUE TITLE
Support Union Types

### ISSUE THREAD

**Issue by yss14** [victorgarciaesgi/simple-graphql-to-typescript#12]
First of all, thank you for this great tool! It addresses and solves the exact problems which have prevented me from using other graphql code generators. Great work!

Are there any plans to support union types? Running `sgts` on my GraphQL endpoint exposing one union type ends in a not-compilable ts file because the type definition for the union type is missing.

GraphQL Schema:
```
type FileUpload {
  container: String!
  blob: String!
  fileExtension: String!
  originalFilename: String!
  hash: String!
  accessUrl: String!
}

union FileSource = FileUpload // more to come in the near future
```

The resulting ts file holds an interface for `FileUpload` and also uses the `FileSource` type for properties where it's referenced in the GraphQL schema, but there is no type definition for the `FileSource` type.

**Comment by victorgarciaesgi** [comment]
Hi @yss14 and thanks! 😀
Union types is a missing feature I wanted to implement but i have no project that rely on it so it was not on my priority list. 
I can work on it when i go back from vacation monday, it would help me a lot if you can provide me a introspection json schema of your graphql api to see how i can identify union types (or endpoint but i suppose it's not public).

Also how do you want it to be shaped in Typescript? 

Something like `type UnionType = Type1 | Type2`?

**Comment by yss14** [comment]
Thanks for the fast response @victorgarciaesgi !
The endpoint is available here: https://api-beta.musicshare.rocks/graphql
`type UnionType = Type1 | Type2` looks good to me, I think that's also the way other code generators handle it.
Thank you for adding this feature!

**Comment by victorgarciaesgi** [comment]
@yss14 Added on 0.7.7! Could you try it and tell me if it works well for you? :D

**Comment by yss14** [comment]
@victorgarciaesgi Works like a charm! Thank you very much :)
