### ISSUE TITLE
ReferenceError: sgtsQL is not defined

### ISSUE THREAD

**Issue by yss14** [victorgarciaesgi/simple-graphql-to-typescript#16]
Hi :D

So one last thing: What's the thing about `sgtsQL`, because I can't find anything about it in the docs.
Since I also use the generated types in some backend-related code, I get `ReferenceError: sgtsQL is not defined` because there is no import for that function in the generated types file.

Is there some way to omit fragement generation?

**Comment by victorgarciaesgi** [comment]
Hi :D 

`sgtsQL` is just an alias for `gql` tag from the package `graphql-tag`.

```ts
import sgtsQL, { DocumentNode } from 'graphql-tag';
```

I've renamed it that way because some extensions like `eslint-plugin-graphql` or `Apollo VScode` search for the term `gql` will try to validate the template and fails.

Can you paste me your config file or flags you pass to sgts? I will debug it! :)

I also have to add a setting to disable fragment generation because it's a bit buggy (Fragment generation is really hard) :(

**Comment by yss14** [comment]
OK, I see.
My current command is `sgts -e https://api-beta.musicshare.rocks/graphql -o ./projects/shared-types/src/GeneratedTypes.ts --customScalars '{\"DateTime\": \"string\", \"OrderUpdate\": \"[string, number]\"}'`

**Comment by victorgarciaesgi** [comment]
I've deployed a quick update that includes `sgtsQL` on all configs so that you are not blocked! (0.7.10) :)

**Comment by yss14** [comment]
> I also have to add a setting to disable fragment generation because it's a bit buggy (Fragment generation is really hard) :(

Thanks for the quick fix. I've just tried it, and the import now works. But it seems that there is some problem with the fragement generation when it comes to union types.
For example

```
union FileSource = FileUpload

type A = {
    someField: String!
    sources: [FileSource!]!
}
```

results in

```
fragement Foo on Bar {
    someField
    sources {}
}
```

which leads to graphql compiler errors.

**Comment by yss14** [comment]
Since as you already mentioned, fragement generation can be pretty hard, a setting to disable fragment generation would be the way to go I think :)

**Comment by victorgarciaesgi** [comment]
Yeah I think I will disable fragment generation by default, there is a lot of cases I didn't take into account. Thanks for the report!

**Comment by victorgarciaesgi** [comment]
@yss14 In `0.8.0` fragments are now disabled by default. Docs updated I put a warning for the new option `gen-fragments`

**Comment by victorgarciaesgi** [comment]
Also just so you know, you can just put a config file `.sgtsrc.js` at root with the options, and your script just have to call `sgts generate`. That way it's cleaner :). It also support environements (`sgts generate testing`)

Exemple:

```js
//  .sgtsrc.js
// @ts-check

/**
 * @type { import("simple-graphql-to-typescript").SgtsConfig }
 */
module.exports = {
  endpoint: process.env.NUXT_ENV_API_URL,
  output: './src/models/__generated.ts',
  codegenMethods: true,
  customScalars: {
    DateTime: 'Date',
    Upload: 'string',
  },
};

```
