### ISSUE TITLE
Will crash if there is no .prettierrc fille

### ISSUE THREAD

**Issue by 3rd** [victorgarciaesgi/simple-graphql-to-typescript#5]
Will get stuck after it fails to load the (missing) .prettierrc:

```
sgts -e http://localhost:3000/graphql -o api.ts -G -A
Running Prettier with your config on the generated output
Error: Cannot find module '../../.prettierrc'
```

**Comment by victorgarciaesgi** [comment]
@3rd Hi thanks for the report, fixing this right now!

**Comment by victorgarciaesgi** [comment]
@3rd fixed on `0.6.9`

**Comment by victorgarciaesgi** [comment]
@3rd Also be aware that options have changed starting `0.6.3`, now it's `--codegen-methods` and `--codegen-react-hooks`
https://sgts.netlify.com/options/codegen-react-hooks.html#exemple

**Comment by 3rd** [comment]
@victorgarciaesgi yep, pasted the wrong line. thanks a lot!
